// ============================================================
//  Core/Models/Recommendation.cs
//  ML-generated investment recommendation
// ============================================================

namespace FinancialPortfolioTracker.Core.Models;

/// <summary>
/// An actionable recommendation generated by the ML engine.
/// </summary>
public class Recommendation
{
    public int            Id               { get; set; }
    public string         Symbol           { get; set; } = string.Empty;
    public RecommendationType Type         { get; set; }
    public string         Title            { get; set; } = string.Empty;
    public string         Description      { get; set; } = string.Empty;
    public double         ConfidenceScore  { get; set; }  // 0–1
    public double         PredictedPrice   { get; set; }
    public double         CurrentPrice     { get; set; }
    public double         TargetPrice      { get; set; }
    public double         StopLoss         { get; set; }
    public string         RiskLevel        { get; set; } = "Moderate";
    public string         TimeHorizon      { get; set; } = "30 days";
    public List<string>   Reasoning        { get; set; } = new();
    public DateTime       GeneratedAt      { get; set; } = DateTime.UtcNow;

    public double PotentialGainPercent =>
        CurrentPrice == 0 ? 0 : (TargetPrice - CurrentPrice) / CurrentPrice * 100.0;

    public string ConfidenceLabel => ConfidenceScore switch
    {
        >= 0.80 => "High",
        >= 0.60 => "Medium",
        >= 0.40 => "Low",
        _       => "Very Low"
    };

    public override string ToString() =>
        $"[{Type}] {Symbol}: {Title} | Confidence: {ConfidenceScore:P0} | " +
        $"Target: ${TargetPrice:N2} ({PotentialGainPercent:+0.00;-0.00}%)";
}

public enum RecommendationType
{
    StrongBuy,
    Buy,
    Hold,
    Sell,
    StrongSell,
    Rebalance,
    DiversifyWarning,
    RiskAlert,
    OpportunityAlert
}
